import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import SwiperAudio from "../components/swiper";

export default function Home() {
  const user = {
    name: "Christophe",
  };

  return (
    <>
      <Head>
        <title>Next_Box</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <header>
          <h1 className="h4">
            🎵 Welcome {user.name}
            <br></br>to the <b className="txtBlue">Next_Box</b>
          </h1>
        </header>
        <main>
          <SwiperAudio />
        </main>

        <footer>
          <div className="grid-container">
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              Powered by{" "}
              <span>
                <Image
                  src="/vercel.svg"
                  alt="Vercel Logo"
                  width={72}
                  height={16}
                />
              </span>{" "}
              & explore by Christophe <b>DELOBEL</b>
            </a>
          </div>
          <Link href="/about">About</Link>
        </footer>
      </div>
    </>
  );
}
